### ISSUE TITLE
Export/import

### ISSUE THREAD

**Issue by orthecreedence** [turtl/js#126]
Need an export/import feature. Would allow users to backup their data without fear of Turtl going down.

Relies on the user settings modal (no issue).

**Comment by gdherbom** [comment]
Hi, 
Why closing this issue? Is there a way to export the notes from the server? Thanks.

**Comment by JulienPalard** [comment]
I too needed it so I wrote a minimalistic version of a backup tool: https://github.com/JulienPalard/turtl-backup

It only allows to download all notes, encrypted, so you can store your backup safely, and later decrypt them as needed. Yet is does *not* offer the way to decrypt them, *only* to backup them. at least for the moment. Oh and it does not implement the import function neither.
