### ISSUE TITLE
Board renaming and deleting errors

### ISSUE THREAD

**Issue by Tletl** [turtl/js#155]
I'm getting an error whenever I'm trying to delete and/or rename boards. Name is originally "Nico.jp" (from nicovideo.jp!) and I wanted to rename it to "Nicovideo".

Whenever I'm renaming, this pops up:

> Error syncing model to API: Internal server error. Please report to andrew@turtl.it (TURTL-ERROR-WRAPPER): Turtl wrapped error: EDIT-BOARD: The value NIL is not of the expected type HASH-TABLE.

Whenever I'm trying to delete, this pops up:

> Error syncing model to API: Validation failed: "Field 'storage'  is not of the expected type INTEGER "

By the way, whenever I tried to copy the error by selecting text with Ctrl + left click, error window scrolled up...and if I click on it, it does it too! I have to be really fast to be able to copy it :P

**Comment by orthecreedence** [comment]
Thanks for posting this, I'll take a look at it when I get some time this week. Sorry for the trouble!

**Comment by orthecreedence** [comment]
Should be fixed in 0.6.0, was a complete re-write.
