### ISSUE TITLE
Feature Request - Integration with Tagspaces

### ISSUE THREAD

**Issue by sunjam** [turtl/js#156]
[Tagspaces](https://github.com/tagspaces/tagspaces) is another nw.js based application that acts an online file manager, which is very promising as a self-hosted Evernote alternative, but lacks the polish and features of turtl.  I'm curious about how it could be combined with turtl core to allow for Encryption support and database compatibility by basically logging into turtl from within Tagspaces.  Extensions have yet to be implemented into Tagspaces, but this would be an awesome way to unite two great projects.  Plus, Tagspaces upcoming ios and Android support would be awesome for turtl.

Tagspaces allows you to set associations so it could theoretically be possible to change the built-in markdown editor to turtl, etc.

**Comment by orthecreedence** [comment]
This is a cool idea. I've checked out tagspaces a bit and thought pretty hard on how they could be integrated. The more I think about it, the more I'm realizing that although the apps do share a common space (node-webkit, note-taking, data tagging) there are enough differences in interface and features that this would be a lot of effort. They are both fairly self-contained applications.

I would have absolutely no problem with Turtl being integrated into Tagspaces, although it looks like they use AGPLv3 while Turtl uses GPLv3 (not sure about the compatibility). 

I'm going to keep this on the list, think about it more, and possibly reach out to them once the Turtl mobile apps are completed. We're currently working pretty tirelessly to get these out the door so we can release sometime in June.

Thanks for the suggestion =].
