### ISSUE TITLE
Markdown checklist support

### ISSUE THREAD

**Issue by bitbybit** [turtl/js#159]
Please add support of markdown checklist/tasklist:

https://github.com/chjj/marked/pull/587
- [ ] example
- [ ] list

**Comment by orthecreedence** [comment]
Cool, subscribed to the issue and will upgrade in Turtl once merged/ready.

**Comment by ldidry** [comment]
Well, maybe this issue can be closed? Since the merge #196 (markdown-it instead of marked) 😄
