### ISSUE TITLE
Curser positioning in edit mode

### ISSUE THREAD

**Issue by sojusnik** [turtl/js#161]
The cursor should be on the same position when opening "edit mode", as it was before closing a note. This is vital for long notes, since you have to scroll to the bottom of a note to continue where one left off - quite annoying especially on the Android version.

**Comment by orthecreedence** [comment]
Not sure I understand. Are you saying that when you hit edit, then re-open, you want the cursor in the text editor to be in the same spot it was when you initially hit "Edit?"

**Comment by sojusnik** [comment]
The cursor should simply remember it's place in the text editor after the note was closed and opened again, to continue where one left off.

**Comment by orthecreedence** [comment]
Ok, this makes sense. Tracked: https://trello.com/c/2vfZM5iu
