### ISSUE TITLE
Distraction free mode

### ISSUE THREAD

**Issue by sojusnik** [turtl/js#162]
Turtl, especially the Android version, would greatly benefit from a so called "distraction free mode", alternatively called "focus mode", where the app runs in fullscreen, to minimize distractions and have a better overview over the typed text. This concept is well implemented in apps like [UberWriter](http://uberwriter.wolfvollprecht.de/) and [FocusWriter](http://gottcode.org/focuswriter/). They could be seen as an inspiration for the future implementation of such a feature. On Android this mode is mostly called "immersive mode". Especially with a black background, with a light font color, and a bluetooth keyboard Turtl would become the ultimate "on the go" notebook.

**Comment by orthecreedence** [comment]
I like this. Would this mainly apply to the text box in the note editor? Maybe there would be an icon in the corner that if you click/tap it, the text box takes up the whole screen? Tracked this: https://trello.com/c/Yx1eX71r but feel free to discuss details further on the github issue, I'm interested in what you would find the most useful.

**Comment by sojusnik** [comment]
Yes, the idea with the icon in the "edit mode" would completely suffice. Upon clicking/tapping only the text should be displayed, without any UI elements, preferably in the [dark mode](https://github.com/turtl/mobile/issues/3).
