### ISSUE TITLE
"Edit note" layout

### ISSUE THREAD

**Issue by sojusnik** [turtl/js#163]
Is there a certain reason, that in "edit note" the second part of the window is completely blank as seen [here](http://i.imgur.com/knHyZkK.png)?

Wouldn't it be better to use this space for the text area? Especially on the Android version this greatly diminishes the text area so that you have to scroll more often.

The area for "boards" and "tags" could also be easily scalled down to a one liner, imho.

**Comment by orthecreedence** [comment]
Yes, the way I'm handling the spacing here is bad and there's no excuse for it. You aren't the first person to not like it, so there's already an item on my list to fix: https://trello.com/c/Q3mJc5dB
