### ISSUE TITLE
Autosaving notes

### ISSUE THREAD

**Issue by sojusnik** [turtl/js#164]
Are notes automatically saved locally on the fly when writing, or only after hitting "edit" with a red dot in "edit note"?

Is there a difference in the behaviour between the desktop and the android version?

I'm asking because I'm sometimes afraid of losing long passages while writing, if the app should crash  for inexplicable reasons.

**Comment by orthecreedence** [comment]
Notes are *not* autosaved and are only saved when clicking the red dot Edit button.

This would be a great feature to support though, and would go nicely with note versioning.

Tracked: https://trello.com/c/Yl5o5eVf
