### ISSUE TITLE
supporting ISO-8859-1

### ISSUE THREAD

**Issue by zevelshlli** [turtl/js#167]
hey,

there is currently a problem with loading Hebrew folders.
Does the program supports Hebrew letters?

**Comment by orthecreedence** [comment]
Can you give me an example of a Hebrew word I can test with?

**Comment by zevelshlli** [comment]
תיקיה is Hebrew for Folder.
in some cases i would get an error of folder not being loaded.
maybe is't because of the folder name (just guessing)

**Comment by orthecreedence** [comment]
Ok, I put this issue on our tracker here: https://trello.com/c/4fxUHW0h
