### ISSUE TITLE
Clicking a Link in a File Note Always Accesses the Note's File

### ISSUE THREAD

**Issue by DWWagner** [turtl/js#188]
When clicking on a markdown generated link while viewing a File note, all links cause the file from the note to be accessed instead of the address of the link.

Linux x64 Client
Installed to ~/.local/turtl with a symlink to ~/.local/bin/turtl
Ubuntu 16.04.1 LTS

Let me know if you need any more info!

**Comment by orthecreedence** [comment]
Fixed here: https://github.com/turtl/js/commit/6acda88205e1ae5a0f2530f29ae1d47a6ebf06f1
