### ISSUE TITLE
Turtl offline?

### ISSUE THREAD

**Issue by bradrice** [turtl/js#191]
It appears Turtl is offline or there are cert problems. I'm trying 9/2/2016

**Comment by de4niih** [comment]
@bradrice Hey mate. I have the same issue. Apparently its offline ;(

**Comment by leon4992** [comment]
Same issue here, i hope we get some information soon.

**Comment by de4niih** [comment]
Unfortunately this morning I noticed the Domain was in redemption mode. I could get back my notes with recovering the IP and add it in my Hosts File.
Also texted the guy on Twitter - no response yet.

But now also the servers are down ;(
2. September 2016 23:27 Uhr, "Leonardo Caggianelli"  schrieb:
	Same issue here, i hope we get some information soon.

**Comment by leon4992** [comment]
Let's see how it goes. I hope there will be a way to recover our notes if things get ugly.

**Comment by orthecreedence** [comment]
Hey, everyone. This was on oversight on my part.

Fix here: https://plus.google.com/102450061192607469656/posts/JDA94PNFEVc
