### ISSUE TITLE
Servers offline?

### ISSUE THREAD

**Issue by sadmansk** [turtl/js#192]
Since about 15 hours ago I haven't been able to connect to the syncing servers, and it seems like the website is down as well, any updates?

**Comment by metractive** [comment]
There is any news about the servers?

**Comment by lqust** [comment]
I managed to connect to the alternative server, but somehow when I log in I don't see my notes from Friday. Are they gone? Is there an estimation on when they will be back?

**Comment by metractive** [comment]
@lqust Would you give us the alternative URL path?

**Comment by rgv151** [comment]
just found it here: https://api.turtlapp.com/v2

**Comment by lqust** [comment]
This is the one

2016-09-05 0:55 GMT-03:00 Huy Doan <notifications@github.com>:

**Comment by sadmansk** [comment]
Servers seems to have come online now, closing the issue.
