### ISSUE TITLE
Add an installer for RaspberryPi

### ISSUE THREAD

**Issue by leolivier** [turtl/js#198]
Hi,
I finally, after a long struggle, managed to install everything needed for Turtl on my RaspberryPI.
I think, RPI is the platform of choice for self hosting such a server and it would be good if an installer (or a docker instance) could be delivered with everything need on RPi

**Comment by Dennis-Mayk** [comment]
any update on this?

**Comment by mat-m** [comment]
I advise @leolivier to submit an update of the readme.md to explain what is needed and the commands he used. This will be a first step, and allow someone wanting to make a script to start faster.

**Comment by leolivier** [comment]
Hi @mat-m, I'm sorry but I worked on this 9 months ago and I totally forgot what I did, now.
Furthermore, I uninstalled rethinkdb which took too many resources on my pi and I'm now using framanotes instead...
